# Generated by Django 6.0.7 on 2026-09-26 16:35

import django.db.models.deletion
import treinos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=treinos.models.foto_exercicio_upload_path)),
                ('legenda', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='treinos.exercicio')),
            ],
            options={
                'verbose_name': 'Foto do Exercício',
                'verbose_name_plural': 'Fotos do Exercício',
                'ordering': ['criado_em'],
            },
        ),
    ]
